[user]
name = "kharf"
email = "khar1@proton.me"

# Configure signing backend as before, but lazily signing only on push.
[signing]
behavior = "drop"
backend = "ssh"
key = "/home/kharf/.ssh/signing.pub"

[git]
sign-on-push = true
subprocess = true

[templates]
commit_trailers = '''
format_signed_off_by_trailer(self)
'''
