[colors.normal]
black = "#262626"
blue = "#33b1ff"
cyan = "#3ddbd9"
green = "#42be65"
magenta = "#ee5396"
red = "#ff7eb6"
white = "#dde1e6"

[colors.primary]
background = "#161616"
foreground = "#f2f4f8"

[font]
size = 11

[font.bold]
family = "GeistMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "GeistMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "GeistMono Nerd Font"
style = "Italic"

[font.normal]
family = "GeistMono Nerd Font"
style = "SemiBold"
