[colors.normal]
black = "#262626"
blue = "#33b1ff"
cyan = "#3ddbd9"
green = "#42be65"
magenta = "#ee5396"
red = "#ff7eb6"
white = "#dde1e6"

[colors.primary]
background = "#161616"
foreground = "#f2f4f8"

[font]
size = 13

[font.bold]
family = "IosevkaTerm Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "IosevkaTerm Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "IosevkaTerm Nerd Font Mono"
style = "Italic"

[font.normal]
family = "IosevkaTerm Nerd Font Mono"
style = "Regular"

[keyboard]
bindings = [
   { key = "8", mods = "Control", action = "ToggleViMode" }
]
