[[language]]
name = "go"
scope = "source.go"
injection-regex = "go"
file-types = ["go"]
roots = ["go.work", "go.mod"]
auto-format = true
comment-token = "//"
language-servers = ["gopls"]
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "cue"
scope = "source.cue"
injection-regex = "cue"
file-types = ["cue"]
roots = ["cue.mod/"]
auto-format = true
comment-token = "//"
language-servers = ["cuelsp"]
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "hcl"
language-servers = ["terraform-ls"]

[language-server.cuelsp]
command = "cue"
args = ["lsp"]
