export XDG_CONFIG_HOME="$HOME/.config"
export USE_GKE_GCLOUD_AUTH_PLUGIN=True
export EDITOR=hx
export KUBE_EDITOR=hx
export GOPRIVATE=github.com/mediamarktsaturn
export KIND_EXPERIMENTAL_PROVIDER=podman

autoload -Uz compinit
compinit
# flux autocompletion
command -v flux >/dev/null && . <(flux completion zsh)

# Key mapping for qwertz
xmodmap -e "keycode 34 = braceleft braceright" 2> /dev/null
xmodmap -e "keycode 47 = parenleft parenright" 2> /dev/null
xmodmap -e "keycode 48 = bracketleft bracketright" 2> /dev/null

# prompt
eval "$(starship init zsh)"
