export XDG_CONFIG_HOME="$HOME/.config"
export USE_GKE_GCLOUD_AUTH_PLUGIN=True
export EDITOR=hx
export KUBE_EDITOR=hx
export GOPRIVATE=github.com/mediamarktsaturn
export KIND_EXPERIMENTAL_PROVIDER=podman
export DOCKER_HOST=unix:///run/user/1000/podman/podman.sock
export TESTCONTAINERS_RYUK_DISABLED=true
export PATH="$PATH:$HOME/.local/bin"
alias cd=z
# prompt
eval "$(starship init zsh)"
# better 'cd'
eval "$(zoxide init zsh)"
