export XDG_CONFIG_HOME="$HOME/.config"
export USE_GKE_GCLOUD_AUTH_PLUGIN=True
export EDITOR=hx
export KUBE_EDITOR=hx
export GOPRIVATE=github.com/mediamarktsaturn
export TESTCONTAINERS_RYUK_DISABLED=true
export PATH="$PATH:$HOME/.local/bin:$HOME/.zvm/bin"
alias k=kubectl
alias cd=z
# prompt
eval "$(starship init zsh)"
# better 'cd'
eval "$(zoxide init zsh)"
