[theme]
theme = "plain"

[theme.overrides]
idle_bg = "#161616"
idle_fg = "#dde1e6"
info_bg = "#78a9ff"
info_fg = "#161616"
good_bg = "#78a9ff"
good_fg = "#161616"
warning_bg = "#ff7eb6"
warning_fg = "#dde1e6"
critical_bg = "#ee5396"
critical_fg = "#dde1e6"
separator = "\ue0b2"
separator_bg = "auto"
separator_fg = "auto"

[icons]
icons = "awesome6"

[[block]]
block = "docker"
interval = 2
socket_path = "/run/user/1000/podman/podman.sock"
format = " $icon $running/$total images: $images "
[block.theme_overrides]
idle_bg = "#ee5396"
idle_fg = "#dde1e6"

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
interval = 20
warning = 20.0
alert = 10.0
[block.theme_overrides]
idle_bg = "#78a9ff"
idle_fg = "#161616"

[[block]]
block = "memory"
format = " $icon $mem_avail.eng(prefix:M)/$mem_total.eng(prefix:M) "
[block.theme_overrides]
idle_bg = "#08bdba"
idle_fg = "#161616"

[[block]]
block = "cpu"
interval = 1
[block.theme_overrides]
idle_bg = "#3dddb9"
idle_fg = "#161616"

[[block]]
block = "sound"
[block.theme_overrides]
idle_bg = "#33b1ff"
idle_fg = "#161616"

[[block]]
block = "time"
interval = 5
[block.format]
full = " $icon $timestamp.datetime(f:'%a %Y-%m-%d %R %Z', l:de_DE) "
short = " $icon $timestamp.datetime(f:%R) "
